#!/bin/bash

echo "===================="
echo " DEVOPS MONITOR TOOL"
echo "===================="

echo "Date: $(date)"
echo ""

echo "CPU Usage:"
uptime

echo "Memory:"
free -h

echo "Disk:"
df -h

echo "Top Processes:"
ps aux --sort=-%cpu | head -5
